name: "Inclui cometario ( Composite)"
description: "Essa action inclui comentario em issues ou PR (Composite)"
author: Edilson Monteiro
inputs:
  GITHUB_TOKEN:
    description: "Token de acesso ao GitHub"
    required: true
  issue-id:
    description: "ID da Issue ou PR"
    required: true
  comment:
    description: "Comentario a ser incluido"
    required: true
  GITHUB_REPOSITORY:
    description: "Id do repositorio"
outputs:
  comment-id: 
    description: "ID do comentario incluido"
    #value: ${{ steps.comment-action.outputs.comment-id }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.issue-id }}
    - ${{ inputs.comment }}
    - ${{ inputs.GITHUB_REPOSITORY }}
